/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "ligature-kt"
include(
  "gaze",
  "idgen",
  "lig",
  "ligature",
  "ligature-http",
  "ligature-http-in-memory",
  "ligature-http-test-suite",
  "ligature-http-xodus",
  "ligature-in-memory",
  "ligature-repl",
  "ligature-test-suite",
  "ligature-xodus",
  "wander"
)

//below line is added for CircleCI
enableFeaturePreview("VERSION_CATALOGS")
