/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "ligature-kt"

include(
    "gaze",
    "idgen",
    "lig",
    "ligature",
    "ligature-http",
    "ligature-http-in-memory",
    "ligature-http-test-suite",
    "ligature-http-xodus",
    "ligature-in-memory",
    "ligature-js",
    "ligature-repl",
    "ligature-test-suite",
    "ligature-xodus",
    "wander"
    )

// below line is added for CircleCI
enableFeaturePreview("VERSION_CATALOGS")

dependencyResolutionManagement {
  versionCatalogs {
    create("libs") {
      library("groovy-core", "org.codehaus.groovy:groovy:3.0.5")
      library("groovy-json", "org.codehaus.groovy:groovy-json:3.0.5")
      library("groovy-nio", "org.codehaus.groovy:groovy-nio:3.0.5")
      library("commons-lang3", "org.apache.commons", "commons-lang3").version {
        strictly("[3.8, 4.0[")
        prefer("3.9")
      }
    }
  }
}
