/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

//plugins {
//    id("dev.ligature.kotlin-library-conventions")
//}
//
//kotlin {
//    sourceSets {
//        commonMain{
//            dependencies {
//            }
//        }
//    }
//}

plugins {
    kotlin("multiplatform")// version "1.7.10"
//    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotest.multiplatform)
}

group = "dev.ligature"
version = "0.1.0-SNAPSHOT"

repositories {
    jcenter()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
}

kotlin {
    jvm()
    //TODO add js
}
