/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.ligature.slonky.kotlin-library-conventions")
}

dependencies {
    api(project(":ligature"))
    implementation("io.kotest:kotest-runner-junit5:4.4.1")
    implementation("io.kotest:kotest-assertions-core:4.4.1")
}
