/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  //id("org.jetbrains.kotlin.jvm")
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  //id("org.jetbrains.kotlin.multiplatform")
  kotlin("multiplatform")
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
//  // Align versions of all Kotlin components
//  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
//
//  // Use the Kotlin JDK 8 standard library.
//  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
//
//  // Align versions of all Kotlin components
//  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
}
